### ISSUE TITLE
In a multi-language site, always return non-translated fields

### ISSUE THREAD

**Issue by andrevvm** [lord-executor/kirby-json-api#2]
If a field is set to translate: false, that field isn't returned for any other language other than the default. You could check if a field is translated with https://getkirby.com/docs/cheatsheet/field-methods/isTranslated, and then return that field in the default language if not.

**Comment by lord-executor** [comment]
Maybe I am not understanding your question properly, because as far as I can tell this is exactly the behavior that the built-in API exhibits:
* if there is **no** content file for the requested language, the default language is loaded
* if there **is** a content file for the requested language, the values from that file are used _unless_ the field (which is present in the content file) has an empty value, in which case it falls back to the field value from the default language.

The `isTranslated` method wouldn't be particularly helpful either since it only declares a field as _untranslated_ if it is explicitly empty or has the exact same value as the default translation. In fact; the only reason to use `isTranslated` would be to **not** include untranslated fields in the JSON output.

**Comment by andrevvm** [comment]
You're right that is the behavior for empty translated fields... I'm referring to fields that are set to `translate: false` in the Blueprint. This is really handy for fields that shouldn't be translated, like phone numbers and addresses. These fields are **only** saved to the content file of the default language, and not even saved as empty fields in the other languages. This actually seems like a bad pattern on behalf of Kirby..

The `isTranslated` method does indeed return `false` for `translate: false` fields, in which case the default language value should be used. However, I'm not even sure that method is needed, as Kirby will return the default language content using the standard `$page->field()` method... But I suppose the API code will work a bit differently?

Thanks for your help, I really do love this plugin!

**Comment by lord-executor** [comment]
Hmm... I still don't understand the question.
* The API **does** exactly what you say it should do.
* It uses the exact same Kirby API's you are describing.

The `translate: false` configuration is purely a panel feature. It doesn't affect any other part of Kirby as far as I can tell.

Can you maybe describe your use case to me and the results that you get versus what you would like to get?

**Comment by andrevvm** [comment]
Any time I set a field to `translate: false`, it does not show in the API JSON results for a non-default language. I've tested this multiple times with the built-in endpoints, as well as custom. It doesn't return empty, the key is just not there at all...

Please try these steps to reproduce:

1. In a multilanguage site, set a field as `translate: false`
2. In the Kirby Panel, save a value to the field in the default language.
3. Switch to any other non-default language, and save. (**Important**)
4. Activate the non-default language in the site, and query the API.
5. You will see the field is not returning in the JSON.
6. You will also see in the content file for that language, the field is not there at all.
7. However, using $page->field() returns the default language value as expected.

Expected behavior: example field is returned in the API in the default language.

If you follow these steps and still get the expected behavior, it must be a problem on my end!

**Comment by lord-executor** [comment]
Sorry it took me so long, but I think now I get it.

The problem here is that when you do `$page->field()` Kirby knows to look for a field `field` because... well... you just told it to. The built-in API doesn't know about any fields that are not in the actual content of the page - it can only iterate over whatever is there and as you say, the `translate: false` fields are simply never stored.

There is not much I can (and am also willing) to do about that in the base API library, but I think I can provide you with a sample on how to get the field out with some of the customization options the plugin provides, but I'm a "bit" busy with work until Friday, so it'll have to wait until then.

**Comment by andrevvm** [comment]
No problem, thanks for your patience! That's what I meant when I said it seems like a bad pattern on behalf of Kirby... I would assume `translate: false` to simply save an empty field for the other languages.

For now I will forego the `translate: false` option, but would really appreciate a customization sample when you have a spare moment.

Thanks!

**Comment by andrevvm** [comment]
Hey, don't worry about spending time on this unless you want to... I've figured out a solution that works for me.

For posterity, I'll post my method here. It isn't the most elegant, but I've basically created my own option `notranslate`. When `true`, I empty the fields, add custom css, and make them readonly via extended panel fields. This way, the fields of non-default languages are always saved empty, and the default values are returned via the API!

**Comment by lord-executor** [comment]
I'm glad you already found a solution, but since I'm trying to find ways to improve the plugin and its documentation anyway, I'm providing an alternative solution here:

The JSON API solution is actually fairly simple; I just had to check to make sure it works as I thought it would. Instead of using the built-in API endpoints - which are convenient, but relatively limited in their current form - you can build your own version quite easily and use the PHP APIs to control the output to your heart's desire. Just put the following code in a file called `jsonapi.extension.php` in a new folder inside your `site/plugins` directory.

```php
<?php

use Lar\JsonApi\JsonApiUtil;
use Lar\JsonApi\PageField;


jsonapi()->register([
	[
		'method' => 'GET',
		'pattern' => "custom/page/(:all)",
		'action' => function ($id) {
			$page = page($id);
			if ($page === false)
				return Response::error('Page not found', 404, ['id' => $id]);

			$result = JsonApiUtil::pageToJson($page);

			// This is the actual customization code
			if ($page->intendedTemplate() === 'myblueprint') {
				// If the blueprint of the page is the one with the untranslatable field,
				// explicitly add a new PageField to the JSON field collection; once the collection
				// "knows" about the field, the rest works automatically
				$result->addField('myUntranslatableField', new PageField($page->myUntranslatableField()));
			}

			return $result;
		},
	],
]);
```

Then with a call like `.../api/custom/page/mypage?lang=es`, the resulting JSON output will always contain the `myUntranslatableField` with the value from the default language if the field does not exist in the content file of the current language.

While analyzing this scenario I have had various ideas on how to make the built-in API more configurable and flexible, but that's going into a Future Version (tm). If you have more suggestions concerning your current use case, let me know.
